"""Initial schema

Revision ID: c08a2cad6d87
Revises: 
Create Date: 2025-12-19 16:41:44.995065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c08a2cad6d87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_report')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'supplier', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('reconciliation_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expected_cash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_cash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('counter_person', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reconciliation_report_pkey')),
    sa.UniqueConstraint('report_date', name=op.f('reconciliation_report_report_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
